# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarketProject', '0003_remove_products_supermarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='supermarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarketProject.Supermarket'),
        ),
    ]
